routes/web.php
<?php



use Illuminate\Support\Facades\Route;



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|

*/



Auth::routes();

Route::get('/register-api', function()
{
    include public_path().'/register_api.php';
});


Route::get('/redirectToUserHome', 'Auth\LoginController@redirectToUserHome');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('pages.about');

Route::get('/terms-conditions', 'HomeController@terms')->name('pages.terms');
Route::get('/privacy-policy', 'HomeController@policy')->name('pages.policy');

Route::get('/footlab', 'HomeController@footlab')->name('pages.footlab');
Route::get('/thankyou/{formType}', 'HomeController@thankYou')->name('form.submission.thankyou');


// Sports
Route::get('/isd-academy', 'HomeController@isdAcademy')->name('pages.isd_academy');

// Route::get('/football', 'HomeController@football')->name('pages.football');
Route::get('/football-venuehire', 'HomeController@footballVenue')->name('pages.football_venue');

Route::get('/tennisacademy', 'HomeController@tennis')->name('pages.tennis');

Route::get('/tennis', function() {
    return redirect('/tennisacademy');
});

Route::get('/tennisacademycamps', 'HomeController@tennisCamp')->name('pages.tennis_camp');

Route::get('/tennisacademy-details', 'HomeController@tennisDetails')->name('pages.tennis_details');

Route::get('/tennisacademy-fees', 'HomeController@tennisFee')->name('pages.tennis_fees');

Route::get('/tennisacademy-schedule', 'HomeController@tennisSchedule')->name('pages.tennis_schedule');

Route::get('/tennis-venuehire', 'HomeController@tennisVenue')->name('pages.tennis_venue');

Route::get('/tennisadults', 'HomeController@tennisAdults')->name('pages.tennis_adults');


Route::get('/dubai30x30', 'HomeController@dubaiFitnessChallenge')->name('pages.dubai_fitness_challenge');

// Route::get('/programs/tennis-program', 'HomeController@tennisProgram')->name('programs.tennis_program');

Route::get('/rugby', 'HomeController@rugby')->name('pages.rugby');

Route::get('/padel', 'HomeController@padel')->name('pages.padel');

Route::get('/athleticsacademy', 'HomeController@athletics')->name('pages.athletics');

Route::get('/athleticsacademycamps', 'HomeController@athleticsCamp')->name('pages.athletics_camp');

// Route::get('/athletics', 'HomeController@athletics')->name('pages.athletics');

// Route::get('/programs/athletics-program', 'HomeController@athleticsProgram')->name('programs.athletics_program');

// Route::get('/isd-athletics', 'HomeController@isdAthletics')->name('pages.isd_athletics');

// Route::get('/athletics-classic-meets', 'HomeController@athleticsClassicMeets')->name('pages.athletics.classic.meets');

// Route::get('/athleticsacademy-details', 'HomeController@athleticsDetails')->name('pages.athletics_details');

Route::get('/athletics', function() {
    return redirect('/athleticsacademy');
});

Route::get('/athleticsacademy-fees', 'HomeController@athleticsFee')->name('pages.athletics_fees');

Route::get('/athleticsacademy-schedule', 'HomeController@athleticsSchedule')->name('pages.athletics_schedule');

Route::get('/athletics-venuehire', 'HomeController@athleticsVenue')->name('pages.athletics_venue');
Route::get('/eupepsia', 'HomeController@eupepsia')->name('pages.eupepsia');



Route::get('/venueHire', 'HomeController@venueHire')->name('venu.hire');

Route::get('/academyRegistration', 'HomeController@academyRegistration')->name('academy.registration');

Route::post('/formSubmission', 'HomeController@registration')->name('form.submission');

Route::post('/inquiryformSubmission', 'HomeController@inquiryform')->name('inquiryform.submission');


Route::name('admin.')->prefix('admin/')->middleware(['admin'])->group(function(){

 Route::get('/', 'SignUpController@index')->name('dashboard');
 Route::get('/searchSignUps', 'SignUpController@searchSignUps')->name('signUps.search');
 Route::get('/{signUp}/edit', 'SignUpController@edit')->name('signUps.edit');
 Route::put('/{signUp}/update', 'SignUpController@update')->name('signUps.update');
 Route::delete('/{signUp}', 'SignUpController@destroy')->name('signUps.delete');
 Route::post('/exportData', 'SignUpController@exportData')->name('export.data');
 Route::post('/export-all-data', 'SignUpController@exportALLData')->name('export.all.data');

 Route::group(['prefix' => 'athletics-meet'], function () {
 Route::get('/', 'SignUpController@indexAthleticsMeet')->name('athletics.meet.index');
  Route::delete('/{signUp}', 'SignUpController@destroy')->name('signUps.delete');
 Route::get('/search', 'SignUpController@searchAthleticsMeet')->name(
 	'athletics.meet.search');

 });

 Route::group(['prefix' => 'tennis'], function () {
 Route::get('/', 'SignUpController@indexTennis')->name('tennis.index');
 Route::post('/export/sign-ups','SignUpController@exportData')->name('tennis.export.data');
 Route::delete('/{signUp}', 'SignUpController@destroy')->name('signUps.delete');
 Route::get('/searchSignUps', 'SignUpController@searchTennisSignUps')->name('tennis.search');

 });

  Route::group(['prefix' => 'pop-up'], function () {
  Route::get('/', 'SignUpController@indexPopUp')->name('popup.index');
 // Route::post('/export/sign-ups','SignUpController@exportData')->name('tennis.export.data');
  Route::delete('/{signUp}', 'SignUpController@destroy')->name('popup.delete');
 // Route::get('/searchSignUps', 'SignUpController@searchTennisSignUps')->name('tennis.search');

 });

  Route::group(['prefix' => 'inquiry'], function () {
 Route::get('/', 'InquiriesController@index')->name('inquiry.index');
  Route::get('/{id}/edit', 'InquiriesController@edit')->name('inquiry.edit');
 Route::put('/{id}/update', 'InquiriesController@update')->name('inquiry.update');
//  Route::post('/export/sign-ups','SignUpController@exportData')->name('tennis.export.data');
 Route::delete('/{id}', 'InquiriesController@destroy')->name('inquiry.delete');
//  Route::get('/searchSignUps', 'SignUpController@searchTennisSignUps')->name('tennis.search');
Route::get('/searchInquiries', 'InquiriesController@searchInquiries')->name('inquiry.search');

 });


 // mr wick
 Route::group(['prefix' => 'contact-leads'], function () {
    Route::get('/', 'ContactLeadsController@index')->name('lead.index');
//      Route::get('/{id}/edit', 'InquiriesController@edit')->name('inquiry.edit');
//     Route::put('/{id}/update', 'InquiriesController@update')->name('inquiry.update');
//    //  Route::post('/export/sign-ups','SignUpController@exportData')->name('tennis.export.data');
//     Route::delete('/{id}', 'InquiriesController@destroy')->name('inquiry.delete');
//    //  Route::get('/searchSignUps', 'SignUpController@searchTennisSignUps')->name('tennis.search');
//    Route::get('/searchInquiries', 'InquiriesController@searchInquiries')->name('inquiry.search');

    });


 });

resources/views/admin/pages/athletics_meet.blade.php
@inject('arrays','App\Http\Utilities\Arrays')
@extends('layouts.admin')
@section('content')
<h3 class="pagetitle">Dashboard</h3>
<section class="box">
  <div class="box-header">
    <p class="box-title">Registration</p>
  </div>
  <div class="box-body">
    {!! Form::open(['route' => 'admin.athletics.meet.search', 'files' => 'true', 'method' => 'GET', 'enctype'=>"multipart/form-data",'class'=>"default-form"]) !!}
    <div class="row">
      
      <div class="col-md-3">
        <div class="control-group">
          {!! Form::text('keyword',$keyword ?? null, ['class'=>'form-field','placeholder' => 'Search By Keyword']) !!}
        </div>
      </div>
      
    <div class="col-md-6">
      <button type="submit" class="btn --btn-small --btn-primary">Search</button>
    </div>
  </div>
    
    {!! Form::close() !!}
    {!! Form::open(['route' => 'admin.export.data', 'method' => 'POST', 'enctype'=>"multipart/form-data"]) !!}
    <button class="btn --btn-small --btn-primary" type="submit" name="submit" value="5">Export Data</button>
    {!! Form::close() !!}
    <table class="table --bordered --hover">
      <thead>
        <tr>
          <th><center>S No</center></th>
          <th>User Details</th>
          <th><center>Event Dates</center></th>
          <th><center>Message</center></th>
          <th><center>Form Type</center></th>
          <th><center>Admin Comments</center></th>
          <th><center>Created At</center></th>
          <th><center>Action</center></th>
        </tr>
      </thead>
      <tbody>
        @foreach ($signUps as $key=>$signUp)
        
        <tr>
          <td><center>{{ $signUps->firstItem() + $key }}</center></td>
          <td>
            
            <strong>User Name:</strong> {{ $signUp->user->name }} <br>
            <strong>Email: </strong> {{ $signUp->user->email }} <br>
            <strong>Contact: </strong> {{ $signUp->user->mobile_no }} <br>
             <strong>Nationality: </strong> {{ $signUp->user->nationality }} <br>
            <strong>Player Name: </strong> @if(!empty($signUp->player_id)){{ $signUp->player->name }}@endif <br>
            <strong>Player DOB: </strong> @if(!empty($signUp->player_id)){{ $signUp->player->dob }} @endif
            
            
          </td>
          <td><center>@if(!empty($signUp->event_date))
            @php $event_dates=json_decode($signUp->event_date,true); @endphp
            
            
            @foreach($event_dates as $key => $date)
            
            {{ $date['eventDate']}}<br>
            
            @endforeach
            @endif
          </center></td>
          <td><center>@if(!empty($signUp->events))
            @php $events=json_decode($signUp->events,true); @endphp
            
            
            @foreach($events as $key => $event)
            
            {{ $event['eventName']}}<br>
            
            @endforeach
            @endif
          </center></td>
          <td><center>{{"Athletes Classic Meets Form"}}</center></td>
          <td><center>
            @if(!empty($signUp->admin_comments))
            @php $comments=json_decode($signUp->admin_comments,true); @endphp
            
            
            @foreach($comments as $key => $comment)
            @if($comment['id']==$signUp->id)
            {{ $comment['comments']}}
            <b>Posted By:</b>{{ $comment['admin_name']}}<br>
            <b>Updated At:</b>{{$comment['posted_on']}}<br>
            @endif
            @endforeach
            
            @endif
          </center></td>
          <td><center>{{  \Carbon\Carbon::parse($signUp->created_at)->format('d/m/Y H:i')}}</center></td>
          <td><center>
            <a href="{{ route('admin.signUps.edit',[$signUp->id]) }}" class="btn --btn-small bg-secondary fc-white">Edit</a>
            <button type="button" class="deleteItem btn --btn-small bg-danger fc-white" data-delete-id="{{ $signUp->id }}" id="deleteItem">Delete</button>
          </td>
        </tr>
        @endforeach
      </tbody>
      
    </table>
    <ul class="pagination">
      {{$signUps->links()}}
    </ul>
  </div>
</section>
<script type="text/javascript">
var dateToday = new Date();
$( "#date_of_birth" ).datepicker({
});
</script>
{!! Form::open(['method' => 'delete', 'id' => 'deleteForm']) !!}
{!! Form::close() !!}
<script>
var deleteResourceUrl = '{{ url("/athletics-meet")}}';
$(document).ready(function () {

$('.deleteItem').click(function (e) {
e.preventDefault();
var deleteId = parseInt($(this).data('deleteId'));

$('#deleteForm').attr('action', deleteResourceUrl + '/' + deleteId);
if (confirm('Are you sure?')) {
$('#deleteForm').submit();
}
});
});
</script>
@endsection

resources/views/admin/pages/dashboard.blade.php
@extends('layouts.admin')
@section('content')
<h3 class="pagetitle">Dashboard</h3>
<section class="box">
    <div class="box-header">
        <p class="box-title">Registration</p>
    </div>
    <div class="box-body">
        {!! Form::open(['route' => 'admin.export.all.data', 'method' => 'POST', 'enctype'=>"multipart/form-data"]) !!}
        <button class="btn --btn-small --btn-primary" type="submit" name="submit" value="6">Export All Data</button>
        {!! Form::close() !!}
        <br>
        {!! Form::open(['route' => 'admin.signUps.search', 'files' => 'true', 'method' => 'GET', 'enctype'=>"multipart/form-data",'class'=>"default-form"]) !!}
        <div class="row">
            
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::text('name',$request->name ?? null, ['class'=>'form-field','placeholder' => 'Search By Name']) !!}
                </div>
            </div>
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::text('email',$request->email ?? null, ['class'=>'form-field','placeholder' => 'Search By Email']) !!}
                </div>
            </div>
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::text('mobile',$request->mobile ?? null, ['class'=>'form-field','placeholder' => 'Search By Mobile']) !!}
                </div>
            </div>
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::select('type',$types,$request->type ?? null, ['class'=>'form-field','placeholder' => 'Search By Form Type']) !!}
                </div>
            </div>
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::text('date_of_requirement',$request->date_of_requirement ?? null, ['class'=>'form-field','id'=>'date_of_requirement', 'placeholder'=>'Player Date of Requirement','autocomplete'=>'off']) !!}
                </div>
            </div>
        </div>
        <button type="submit" class="btn --btn-small --btn-primary">Search</button>
        <a href="{{route('admin.dashboard')}}"><button type="button" class="btn --btn-small --btn-danger">Clear</button></a>
        {!! Form::close() !!}
        {!! Form::open(['route' => 'admin.export.data', 'method' => 'POST', 'enctype'=>"multipart/form-data"]) !!}
        <button class="btn --btn-small --btn-primary" type="submit" name="submit" value="1">Export Venu Hire Registration Data</button>
        <button class="btn --btn-small --btn-primary" type="submit" name="submit" value="2">Export Academy Registration Data</button>
        <button class="btn --btn-small --btn-primary" type="submit" name="submit" value="3">Export Contact Form Data</button>
        {!! Form::close() !!}
        
        <div class="table-responsive">
            <table class="table --bordered --hover">
                <thead>
                    <tr>
                        <th width="5%"><center>S No</center></th>
                        <th width="15%">User Details</th>
                        <th width="40%"><center>Message</center></th>
                        <th width="30%"><center>Admin Comments</center></th>
                        <th width="10%"><center>Created At</center></th>
                        <th width="10%"><center>Action</center></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($signUps as $key=>$signUp)
                    
                    <tr>
                        <td><center>{{ $signUps->firstItem() + $key }}</center></td>
                        <td>
                            <strong>Sports: </strong>
                            @if(!empty($signUp->sport_id))
                            {{$signUp->sport->name}}
                            @endif <br>
                            
                            <strong>User Name:</strong> {{ $signUp->user->name }} <br>
                            <strong>Email: </strong> {{ $signUp->user->email }} <br>
                            <strong>Contact: </strong> {{ $signUp->user->mobile_no }} <br>
                           
                            <strong>Player Name: </strong> @if(!empty($signUp->player_id)){{ $signUp->player->name }}@endif <br>
                            <strong>Player DOB: </strong> @if(!empty($signUp->player_id)){{ $signUp->player->dob }}<br>

                            <strong>Player Type: </strong> @if($signUp->is_adult == 1 && $signUp->sport_id==4){{"Adult" }} @elseif($signUp->is_adult == 1 && $signUp->sport_id==5){{"Adult" }}@endif
                            @endif <br>
                            <strong>Source: </strong> {{ $signUp->source }}<br>
                            <strong>Form Type: </strong>
                            @if(!empty($signUp->form_type_id))
                            {{$signUp->formType->name}}
                            @endif <br>
                            @if($signUp->form_type_id==TYPE_VENUE)
                            <strong>Date of Requirement: </strong>
                            {{ $signUp->date_of_requirment}}
                             @endif
                        </td>
                        
                        <td><center>{{ $signUp->message }}</center></td>
                        <td><center>
                            @if(!empty($signUp->admin_comments))
                            @php $comments=json_decode($signUp->admin_comments,true); @endphp
                            
                            
                            @foreach($comments as $key => $comment)
                            @if($comment['id']==$signUp->id)
                            {{ $comment['comments']}} <br>
                            <b>Posted By: </b>{{"Admin"}}<br>
                            <b>Updated At: </b>{{$comment['posted_on']}}<br>
                            @endif
                            @endforeach
                            
                            @endif
                        </center></td>
                        <td><center>
                            <p>
                                {{  \Carbon\Carbon::parse($signUp->created_at)->format('d/m/Y H:i')}}
                            </p>
                            </center>
                        </td>
                        <td><center>
                            <a href="{{ route('admin.signUps.edit',[$signUp->id]) }}" class="btn --btn-small bg-secondary fc-white">Edit</a>
                            <button type="button" class="deleteItem btn --btn-small bg-danger fc-white" data-delete-id="{{ $signUp->id }}" id="deleteItem">Delete</button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
                
            </table>
        </div>
        <ul class="pagination">
            @if(isset($request))
            {{ $signUps->appends(Request::all())->links() }}
            @else
            {{$signUps->links()}}
            @endif
            
        </ul>
    </div>
</section>
<script type="text/javascript">
var dateToday = new Date();
$( "#date_of_requirement" ).datepicker({
});
</script>
{!! Form::open(['method' => 'delete', 'id' => 'deleteForm']) !!}
{!! Form::close() !!}
<script>
var deleteResourceUrl = '{{ url("/admin") }}';
$(document).ready(function () {

$('.deleteItem').click(function (e) {
e.preventDefault();
var deleteId = parseInt($(this).data('deleteId'));

$('#deleteForm').attr('action', deleteResourceUrl + '/' + deleteId);
if (confirm('Are you sure?')) {
$('#deleteForm').submit();
}
});
});
</script>
@endsection

resources/views/admin/pages/inquiry-form.blade.php
@extends('layouts.admin')
@section('content')
<h3 class="pagetitle">Acedemy Inquiries </h3>
<section class="box">
    
    
  <div class="box-body">
    {!! Form::open(['route' => 'admin.inquiry.search', 'files' => 'true', 'method' => 'GET', 'enctype'=>"multipart/form-data",'class'=>"default-form"]) !!}
        <div class="row">
            
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::text('name',$name ?? null, ['class'=>'form-field','placeholder' => 'Search By Name']) !!}
                </div>
            </div>
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::text('email',$email ?? null, ['class'=>'form-field','placeholder' => 'Search By Email']) !!}
                </div>
            </div>
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::text('mobile',$mobile ?? null, ['class'=>'form-field','placeholder' => 'Search By Mobile']) !!}
                </div>
            </div>
         
            <div class="col-md-3">
                <div class="control-group">
                    {!! Form::text('date',$date ?? null, ['class'=>'form-field','id'=>'date_of_requirement', 'placeholder'=>'Search By Date','autocomplete'=>'off']) !!}
                </div>
            </div>

        </div>

        <button type="submit" class="btn --btn-small --btn-primary">Search</button>
        {!! Form::close() !!}
        {!! Form::open(['route' => 'admin.tennis.export.data', 'method' => 'POST', 'enctype'=>"multipart/form-data"]) !!}
        <button class="btn --btn-small --btn-primary" type="submit" name="submit" value={{TYPE_VENUE}}>Export Venu Hire Registration Data</button>
        <button class="btn --btn-small --btn-primary" type="submit" name="submit" value={{TYPE_ACADEMY}}>Export Academy Registration Data</button>
        <!-- <button class="btn --btn-small --btn-primary" type="submit" name="submit" value="3">Export Contact Form Data</button>-->
        {!! Form::close() !!} 
    
    
    
    @if(session()->has('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
@endif
  
    <table class="table --bordered --hover">
      <thead>
        <tr>
          <th width="5%"><center>S No</center></th>
          <th><center>Sport</center></th>
          <th>User Detail</th>
          <th><center>Description</center></th>
          <th><center>Date</center></th>
          <th><center>Admin Comments</center></th>
          <th><center>Action</center></th>
        </tr>
      </thead>
      <tbody>
        @foreach ($inquires as $key=>$inquires)
        
        <tr>
          <td><center>{{ $inquires->id }}</center></td>
          <td>
            @if(!empty($inquires->sport_id)){{ $inquires->sport->name }}@endif</td>
          <td>
            <strong>Name:</strong> {{ $inquires->name }} <br>
            <strong>Email: </strong> {{ $inquires->email }} <br>
            <strong>Contact: </strong> {{ $inquires->number }} <br>
            </center>
            </td>
            <td>
                {{ $inquires->message }}
          </td>
          <td><center>
            <p>
              {{  \Carbon\Carbon::parse($inquires->date)->format('d/m/Y')}}
            </p>
            </center>
          </td>
          <td>
            @if(!empty($inquires->admin_comments))
            @php $comments=json_decode($inquires->admin_comments,true); @endphp
            
            @foreach($comments as $key => $comment)
            @if($comment['id']==$inquires->id)
            <b>Comment: </b>{{ $comment['comments']}}<br>
            <b>Posted By: </b>{{"Admin"}}<br>
            <br>
            @endif
            @endforeach
            
            @endif
          </td>
          <td><center>
            <a href="{{ route('admin.inquiry.edit',[$inquires->id]) }}" class="btn --btn-small bg-secondary fc-white">Edit</a>
            <button type="button" class="deleteItem btn --btn-small bg-danger fc-white" data-delete-id="{{ $inquires->id }}" id="deleteItem">Delete</button>
          </td>
        </tr>
        @endforeach
      </tbody>
      
    </table>
    <ul class="pagination">
    </ul>
  </div>
</section>
<script type="text/javascript">
var dateToday = new Date();
$( "#date_of_requirement" ).datepicker({
       dateFormat: 'yy-mm-dd',
               changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
});
</script>
{!! Form::open(['method' => 'delete', 'id' => 'deleteForm']) !!}
{!! Form::close() !!}
<script>
var deleteResourceUrl = '{{ url()->current() }}';
$(document).ready(function () {

$('.deleteItem').click(function (e) {
e.preventDefault();
var deleteId = parseInt($(this).data('deleteId'));

$('#deleteForm').attr('action', deleteResourceUrl + '/' + deleteId);
if (confirm('Are you sure?')) {
$('#deleteForm').submit();
}
});
});
</script>
@endsection

resources/views/admin/pages/pop-form.blade.php
@extends('layouts.admin')
@section('content')
<h3 class="pagetitle">PopUp SignUps </h3>
<section class="box">
  <div class="box-header">
    <p class="box-title">Registration</p>
  </div>
  <div class="box-body">
    
    <table class="table --bordered --hover">
      <thead>
        <tr>
          <th width="5%"><center>S No</center></th>
          <th>Parent  Details</th>
          <th>Player Details</th>
          <th><center>Admin Comments</center></th>
          <th><center>Created At</center></th>
          <th><center>Action</center></th>
        </tr>
      </thead>
      <tbody>
        @foreach ($signUps as $key=>$signUp)
        
        <tr>
          <td><center>{{ $signUps->firstItem() + $key }}</center></td>
          <td>
            <strong>Sports: </strong>
            @if(!empty($signUp->sport_id)){{ $signUp->sport->name }}@endif
            <br>
            <strong>User Name:</strong> {{ $signUp->user->name }} <br>
            <strong>Email: </strong> {{ $signUp->user->email }} <br>
            <strong>Contact: </strong> {{ $signUp->user->mobile_no }} <br>
            </center></td>
            <td><center>
            <strong>Player Name: </strong> @if(!empty($signUp->player_id)){{ $signUp->player->name }}@endif <br>
            <strong>Player DOB: </strong> @if(!empty($signUp->player_id)){{ $signUp->player->dob }} @endif
          </center>
          </td>
          
          <td><center>
            @if(!empty($signUp->admin_comments))
            @php $comments=json_decode($signUp->admin_comments,true); @endphp
            
            
            @foreach($comments as $key => $comment)
            @if($comment['id']==$signUp->id)
            {{ $comment['comments']}}<br>
            <b>Posted By:</b>{{"Admin"}}<br>
            <b>Updated At:</b>{{$comment['posted_on']}}<br>
            @endif
            @endforeach
            
            @endif
          </center></td>
          <td><center>
            <p>
              {{  \Carbon\Carbon::parse($signUp->created_at)->format('d/m/Y H:i')}}
            </p>
            </center>
          </td>
          <td><center>
            <a href="{{ route('admin.signUps.edit',[$signUp->id]) }}" class="btn --btn-small bg-secondary fc-white">Edit</a>
            <button type="button" class="deleteItem btn --btn-small bg-danger fc-white" data-delete-id="{{ $signUp->id }}" id="deleteItem">Delete</button>
          </td>
        </tr>
        @endforeach
      </tbody>
      
    </table>
    <ul class="pagination">
      {{$signUps->links()}}
    </ul>
  </div>
</section>
<script type="text/javascript">
var dateToday = new Date();
$( "#date_of_requirement" ).datepicker({
});
</script>
{!! Form::open(['method' => 'delete', 'id' => 'deleteForm']) !!}
{!! Form::close() !!}
<script>
var deleteResourceUrl = '{{ url("/pop-up") }}';
$(document).ready(function () {

$('.deleteItem').click(function (e) {
e.preventDefault();
var deleteId = parseInt($(this).data('deleteId'));

$('#deleteForm').attr('action', deleteResourceUrl + '/' + deleteId);
if (confirm('Are you sure?')) {
$('#deleteForm').submit();
}
});
});
</script>
@endsection