routes/web.php
<?php



use Illuminate\Support\Facades\Route;



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|

*/



Auth::routes();

Route::get('/register-api', function()
{
    include public_path().'/register_api.php';
});


Route::get('/redirectToUserHome', 'Auth\LoginController@redirectToUserHome');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('pages.about');

Route::get('/terms-conditions', 'HomeController@terms')->name('pages.terms');
Route::get('/privacy-policy', 'HomeController@policy')->name('pages.policy');

Route::get('/footlab', 'HomeController@footlab')->name('pages.footlab');
Route::get('/thankyou/{formType}', 'HomeController@thankYou')->name('form.submission.thankyou');


// Sports
Route::get('/isd-academy', 'HomeController@isdAcademy')->name('pages.isd_academy');

// Route::get('/football', 'HomeController@football')->name('pages.football');
Route::get('/football-venuehire', 'HomeController@footballVenue')->name('pages.football_venue');

Route::get('/tennisacademy', 'HomeController@tennis')->name('pages.tennis');

Route::get('/tennis', function() {
    return redirect('/tennisacademy');
});

Route::get('/tennisacademycamps', 'HomeController@tennisCamp')->name('pages.tennis_camp');

Route::get('/tennisacademy-details', 'HomeController@tennisDetails')->name('pages.tennis_details');

Route::get('/tennisacademy-fees', 'HomeController@tennisFee')->name('pages.tennis_fees');

Route::get('/tennisacademy-schedule', 'HomeController@tennisSchedule')->name('pages.tennis_schedule');

Route::get('/tennis-venuehire', 'HomeController@tennisVenue')->name('pages.tennis_venue');

Route::get('/tennisadults', 'HomeController@tennisAdults')->name('pages.tennis_adults');


Route::get('/dubai30x30', 'HomeController@dubaiFitnessChallenge')->name('pages.dubai_fitness_challenge');

// Route::get('/programs/tennis-program', 'HomeController@tennisProgram')->name('programs.tennis_program');

Route::get('/rugby', 'HomeController@rugby')->name('pages.rugby');

Route::get('/padel', 'HomeController@padel')->name('pages.padel');

Route::get('/athleticsacademy', 'HomeController@athletics')->name('pages.athletics');

Route::get('/athleticsacademycamps', 'HomeController@athleticsCamp')->name('pages.athletics_camp');

// Route::get('/athletics', 'HomeController@athletics')->name('pages.athletics');

// Route::get('/programs/athletics-program', 'HomeController@athleticsProgram')->name('programs.athletics_program');

// Route::get('/isd-athletics', 'HomeController@isdAthletics')->name('pages.isd_athletics');

// Route::get('/athletics-classic-meets', 'HomeController@athleticsClassicMeets')->name('pages.athletics.classic.meets');

// Route::get('/athleticsacademy-details', 'HomeController@athleticsDetails')->name('pages.athletics_details');

Route::get('/athletics', function() {
    return redirect('/athleticsacademy');
});

Route::get('/athleticsacademy-fees', 'HomeController@athleticsFee')->name('pages.athletics_fees');

Route::get('/athleticsacademy-schedule', 'HomeController@athleticsSchedule')->name('pages.athletics_schedule');

Route::get('/athletics-venuehire', 'HomeController@athleticsVenue')->name('pages.athletics_venue');
Route::get('/eupepsia', 'HomeController@eupepsia')->name('pages.eupepsia');



Route::get('/venueHire', 'HomeController@venueHire')->name('venu.hire');

Route::get('/academyRegistration', 'HomeController@academyRegistration')->name('academy.registration');

Route::post('/formSubmission', 'HomeController@registration')->name('form.submission');

Route::post('/inquiryformSubmission', 'HomeController@inquiryform')->name('inquiryform.submission');


Route::name('admin.')->prefix('admin/')->middleware(['admin'])->group(function(){

 Route::get('/', 'SignUpController@index')->name('dashboard');
 Route::get('/searchSignUps', 'SignUpController@searchSignUps')->name('signUps.search');
 Route::get('/{signUp}/edit', 'SignUpController@edit')->name('signUps.edit');
 Route::put('/{signUp}/update', 'SignUpController@update')->name('signUps.update');
 Route::delete('/{signUp}', 'SignUpController@destroy')->name('signUps.delete');
 Route::post('/exportData', 'SignUpController@exportData')->name('export.data');
 Route::post('/export-all-data', 'SignUpController@exportALLData')->name('export.all.data');

 Route::group(['prefix' => 'athletics-meet'], function () {
 Route::get('/', 'SignUpController@indexAthleticsMeet')->name('athletics.meet.index');
  Route::delete('/{signUp}', 'SignUpController@destroy')->name('signUps.delete');
 Route::get('/search', 'SignUpController@searchAthleticsMeet')->name(
 	'athletics.meet.search');

 });

 Route::group(['prefix' => 'tennis'], function () {
 Route::get('/', 'SignUpController@indexTennis')->name('tennis.index');
 Route::post('/export/sign-ups','SignUpController@exportData')->name('tennis.export.data');
 Route::delete('/{signUp}', 'SignUpController@destroy')->name('signUps.delete');
 Route::get('/searchSignUps', 'SignUpController@searchTennisSignUps')->name('tennis.search');

 });

  Route::group(['prefix' => 'pop-up'], function () {
  Route::get('/', 'SignUpController@indexPopUp')->name('popup.index');
 // Route::post('/export/sign-ups','SignUpController@exportData')->name('tennis.export.data');
  Route::delete('/{signUp}', 'SignUpController@destroy')->name('popup.delete');
 // Route::get('/searchSignUps', 'SignUpController@searchTennisSignUps')->name('tennis.search');

 });

  Route::group(['prefix' => 'inquiry'], function () {
 Route::get('/', 'InquiriesController@index')->name('inquiry.index');
  Route::get('/{id}/edit', 'InquiriesController@edit')->name('inquiry.edit');
 Route::put('/{id}/update', 'InquiriesController@update')->name('inquiry.update');
//  Route::post('/export/sign-ups','SignUpController@exportData')->name('tennis.export.data');
 Route::delete('/{id}', 'InquiriesController@destroy')->name('inquiry.delete');
//  Route::get('/searchSignUps', 'SignUpController@searchTennisSignUps')->name('tennis.search');
Route::get('/searchInquiries', 'InquiriesController@searchInquiries')->name('inquiry.search');

 });


 // mr wick
 Route::group(['prefix' => 'contact-leads'], function () {
    Route::get('/', 'ContactLeadsController@index')->name('lead.index');
//      Route::get('/{id}/edit', 'InquiriesController@edit')->name('inquiry.edit');
//     Route::put('/{id}/update', 'InquiriesController@update')->name('inquiry.update');
//    //  Route::post('/export/sign-ups','SignUpController@exportData')->name('tennis.export.data');
//     Route::delete('/{id}', 'InquiriesController@destroy')->name('inquiry.delete');
//    //  Route::get('/searchSignUps', 'SignUpController@searchTennisSignUps')->name('tennis.search');
//    Route::get('/searchInquiries', 'InquiriesController@searchInquiries')->name('inquiry.search');

    });


 });

resources/views/includes/academy_form.blade.php
<div class="box --registration-box">
	{!! Form::open(['route' => 'form.submission', 'files' => 'true', 'method' => 'POST', 'enctype'=>"multipart/form-data",'class'=>"default-form --registration-form"]) !!}
	<div class="control-group{{ $errors->has('sport_id') ? ' has-error' : '' }}">
		{!! Form::select('sport_id',$sports,$sport_id ?? null, ['class'=>'form-field','required' => 'required','placeholder' => 'Select Sports','id'=>'sport']) !!}
		@if ($errors->has('sport_id'))
		<span class="form-error" role="alert">
			<strong>{{ $errors->first('sport_id') }}</strong>
		</span>
		@endif
	</div>
	
	{{--<div class="control-group{{ $errors->has('programs') ? ' has-error' : '' }}" style="display: none;" id="program">
		{!! Form::select('program',$programs,null, ['class'=>'form-field','placeholder' => 'Select Program']) !!}
		@if ($errors->has('programs'))
		<span class="form-error" role="alert">
			<strong>{{ $errors->first('programs') }}</strong>
		</span>
		@endif
	</div>--}}

	<div class="control-group{{ $errors->has('player_types') ? ' has-error' : '' }}" style="display: none;" id="player_types">
		{!! Form::select('player_types',$player_types,null, ['class'=>'form-field','placeholder' => 'Select Player Type']) !!}
		@if ($errors->has('player_types'))
		<span class="form-error" role="alert">
			<strong>{{ $errors->first('player_types') }}</strong>
		</span>
		@endif
	</div>
    
	<div class="control-group{{ $errors->has('player_name') ? ' has-error' : '' }}">
		{!! Form::text('player_name', null, ['class'=>'form-field','required' => 'required', 'placeholder'=>'Player Name','id'=>'player_name','autocomplete'=>'off']) !!}
		@if ($errors->has('player_nam'))
		<span class="form-error">
			<strong>{{ $errors->first('player_name') }}</strong>
		</span>
		@endif
	</div>
	
	<div class="control-group{{ $errors->has('dob') ? ' has-error' : '' }}">
		{!! Form::text('dob', null, ['class'=>'form-field','required' => 'required','id'=>'dob', 'placeholder'=>'Player DOB','autocomplete'=>'off']) !!}
		@if ($errors->has('dob'))
		<span class="form-error">
			<strong>{{ $errors->first('dob') }}</strong>
		</span>
		@endif
	</div>
	
	<div class="control-group{{ $errors->has('name') ? ' has-error' : '' }}">
		{!! Form::text('name', null, ['class'=>'form-field', 'placeholder'=>'Parent/Guardian Name', 'id'=>'parent_name','autocomplete'=>'off']) !!}
		@if ($errors->has('name'))
		<span class="form-error">
			<strong>{{ $errors->first('name') }}</strong>
		</span>
		@endif
	</div>
	<div class="control-group{{ $errors->has('email') ? ' has-error' : '' }}">
		{!! Form::text('email', null, ['class'=>'form-field','required' => 'required', 'placeholder'=>'Parent/ Guardian Email', 'id'=>'email']) !!}
		@if ($errors->has('email'))
		<span class="form-error">
			<strong>{{ $errors->first('email') }}</strong>
		</span>
		@endif
	</div>
	<div class="control-group{{ $errors->has('mobile') ? ' has-error' : '' }}">
		{!! Form::text('mobile', null, ['class'=>'form-field','required' => 'required', 'placeholder'=>'Parent/Guardian Mobile','id'=>'mobile']) !!}
		@if ($errors->has('mobile'))
		<span class="form-error">
			<strong>{{ $errors->first('mobile') }}</strong>
		</span>
		@endif
	</div>

       <div class="control-group{{ $errors->has('g-recaptcha-response') ? ' has-error' : '' }}">
            <div class="g-recaptcha" data-sitekey="{{env('NOCAPTCHA_SITEKEY')}}"></div>
            @if ($errors->has('g-recaptcha-response'))
                <span class="help-block">
                    <strong>{{ $errors->first('g-recaptcha-response') }}</strong>
                </span>
            @endif
       
    </div>
	
	
	<div class="control-group mb-10">
		<button type="submit" class="btn --btn-primary">
		{{ __('Register') }}
		</button>
	</div>
	{!! Form::hidden('form_type_id',TYPE_ACADEMY, ['class'=>'form-field']) !!}
	
	<?php /*<p class="maindesc fc-white mb-0">Already have an account? <a href="/login" class="fc-white td-underline">Login</a></p> */?>
	{!! Form::close() !!}
</div>

resources/views/includes/admin_navigation.blade.php
<section class="topbar-nav">

    <nav class="topbar-navigation clearfix">
        <!-- <ul class="unstyled inline float-left">
				<li>
						<a href="#">Administrator</a>
				</li>
		</ul> -->
        <ul class="unstyled inline float-right text-right">
            <li>
                <a href="{{route('logout')}}">
                    <i class="xxicon icon-log-out"></i>
                    Log Out
                </a>
            </li>
        </ul>
    </nav>
</section>
<section class="side-bar">
    <div class="header-logo">
        <img src="/admin-assets-web/images/header-logo.png" alt="" />
    </div>
    <div class="header-user">
        <span class="user-img">
            <img src="/admin-assets-web/images/user.jpg" alt="">
        </span>
        <span class="username">
            Administrator
        </span>
    </div>
    <nav class="primary-navigation">
        <ul class="unstyled">
            <li>
                <a href="{{route('admin.dashboard')}}" class="active">
                    <i class="xxicon icon-home"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{{route('admin.athletics.meet.index')}}">
                    <i class="xxicon icon-home"></i>
                    <span>Athletics Meet</span>
                </a>
            </li>
            <li>
                <a href="{{route('admin.tennis.index')}}">
                    <i class="xxicon icon-home"></i>
                    <span>Tennis</span>
                </a>
            </li>
            <li>
                <a href="{{route('admin.popup.index')}}">
                    <i class="xxicon icon-home"></i>
                    <span>PopUp SignUps</span>
                </a>
            </li>
            <li>
                <a href="{{route('admin.inquiry.index')}}">
                    <i class="xxicon icon-home"></i>
                    <span>Academy Inquiries</span>
                </a>
            </li>
            </li>
            <li>
                <a href="{{route('admin.lead.index')}}">
                    <i class="xxicon icon-home"></i>
                    <span>Contact Leads</span>
                </a>
            </li>
        </ul>
    </nav>
</section>

resources/views/includes/footer.blade.php
<footer class="primary-footer">
	<div class="container-wrapper">

        <div class="reach-out-section">
            <h2 class="title">
                reach out.
                <img src="/assets-web/images/icons/message.svg" alt="" class="d-none d-md-block message-icon">
            </h2>

            <div class="d-md-flex align-items-center justify-content-between">
                <ul class="unstyled inline footer-links">
                    <li>
                        <a href="https://goo.gl/maps/BF3ZoEhZhjau3o8b6" target="_blank">LOCATION</a>
                    </li>

                    <li>
                        <a href="/about">ABOUT</a>
                    </li>

                    <li>
                        <a href="/privacy-policy">PRIVACY POLICY</a>
                    </li>

                    <li>
                        <a href="/terms-conditions">TERMS &AMP; CONDITIONS</a>
                    </li>
                </ul>

                <ul class="unstyled inline social-links">
                    <li>
                        <a href="https://www.instagram.com/ISD_DUBAI/" target="_blank">
                            <img src="/assets-web/images/icons/instagram.svg" alt="ISD Instagram">
                        </a>
                    </li>

                    <li>
                        <a href="https://www.facebook.com/InspiratusSportsDistrict" target="_blank">
                            <img src="/assets-web/images/icons/facebook.svg" alt="ISD Facebook">
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="copyright">
            <p class="title">
                &copy; isd dubai sports city. uae 2021
            </p>
        </div>
    </div>
</footer>

resources/views/includes/navigation.blade.php
<?php
$route=Request::segment(1);	
?>
<div class="" style="background: black;">
    <div class="container-wrapper">
        <div class="row align-items-center">
            <div class="col-md-12">
                <ul class="unstyled inline social-links text-md-right text-right">
                    <li>
                        <a href="https://www.facebook.com/InspiratusSportsDistrict" target="_blank">
                            <i class="fa fa-facebook icon"></i>
                        </a>
                    </li>
                        <li>
                        <a href="https://www.instagram.com/ISD_DUBAI/" target="_blank">
                            <i class="fa fa-instagram icon"></i>
                        </a>
                    </li>
                 
                </ul>
            </div>
        </div>
    </div>
</div>
<header class="primary-header">
	<div class="container-wrapper">
		<div class="row align-items-center">
			<div class="col-3">
				@if(!empty($route) && $route=="isd-academy")
					<a href="/" class="header-logo --innerpage animsition-link">
						<img src="/assets-web/images/logos/isddubai-academy-color.svg" alt="">
					</a>
				@else
					<a href="/" class="header-logo --homepage animsition-link">
						<img src="/assets-web/images/logos/isddubai-color.svg" alt="">
					</a>

					<a href="/" class="header-logo --innerpage animsition-link">
						<img src="/assets-web/images/logos/isddubai-color.svg" alt="">
					</a>
				@endif

			</div>
			<div class="col-9 text-right">
				<!-- <div class="register-button">
					<a href="#" class="btn --btn-secondary">Login/register</a>
				</div> -->

				<div class="primary-navigation">

					<nav class="header-navigation">
						<ul class="unstyled">
							<li>
								<a href="/about" class="animsition-link">about</a>
							</li>

							<li>
								<a href="#">academies</a>

								<ul class="unstyled dropdown">
									<li>
										<a href="https://ae.laligacademy.com/" class="animsition-link">Football</a>
									</li>

									<li>
										<a href="/tennisacademy" class="animsition-link">Tennis</a>
									</li>

									<li>
										<a href="/athleticsacademy" class="animsition-link">Athletics</a>
									</li>

									{{-- <li>
										<a href="#">Padel</a>
									</li> --}}
								</ul>
							</li>

							{{--<li>
								<a href="/isd-academy" class="animsition-link">ISD Academy</a>
							</li>--}}

							{{--<li>
								<a href="#">camps</a>

								<ul class="unstyled dropdown">

									<li>
										<a href="/tennisacademy" class="animsition-link">Tennis</a>
									</li>
									
									<li>
										<a href="/athleticsacademycamps" class="animsition-link">Athletics</a>
									</li>

									<li>
										<a href="#">Padel</a>
									</li>
								</ul>
							</li> --}}

							<li>
								<a href="#">venue rentals</a>

								<ul class="unstyled dropdown">
									<li>
										<a href="/football-venuehire" class="animsition-link">Football</a>
									</li>

									<li>
										<a href="/tennis-venuehire" class="animsition-link">Tennis</a>
									</li>

									<li>
										<a href="/athletics-venuehire" class="animsition-link">Athletics</a>
									</li>

								</ul>
							</li>

							<li>
								<a href="/eupepsia" class="animsition-link">eupepsia</a> 
							</li>

							<li>
								<a href="/footlab" class="animsition-link">footlab</a>
							</li>
						</ul>
					</nav>
					
					<!-- Mobile Navigation Button Start-->
					{{-- <div class="mobile-nav-btn d-lg-none">
					    <span class="lines"></span>
					    <span class="lines"></span>
					    <span class="lines"></span>
					    <span class="lines"></span>
					</div> --}}
					<!-- Mobile Navigation Button End-->
				</div>
				

			</div>
		</div>
	</div>
</header>

resources/views/includes/popup-form.blade.php
<?php
$route=Request::segment(1);	
?>
<section class="popup-form x-modal hidden">
	<div class="modal-content">
		<a href="javascript:;" class="close-btn modal-close">
			<i class="icon xicon-close"></i>
		</a>
		<div class="inner-content">
			@if(!empty($route) && $route=="tennisacademy" || $route=="tennisacademy-fees" || $route=="tennisacademy-schedule")
				<h2 class="title fc-white mb-10">Register Now</h2>
				<picture class="d-block mb-30">
					<img src="https://isddubai.com/assets-web/images/tennis-popup-banner.jpg" alt="">
				</picture>
			@elseif(!empty($route) && $route=="athleticsacademy" || $route=="athleticsacademy-fees" || $route=="athleticsacademy-schedule")
				<picture class="d-block mb-30">
					<img src="https://isddubai.com/assets-web/images/athletics-popup-banner.jpg" alt="">
				</picture>
			@else
				<h4 class="title fc-white mb-10">Enquire Now</h4>
				<picture class="d-block mb-30">
					<img src="https://isddubai.com/assets-web/images/popup-banner.jpg" alt="">
				</picture>
			@endif

			{!! Form::open(['route' => 'form.submission', 'files' => 'true', 'method' => 'POST', 'enctype'=>"multipart/form-data",'class'=>"default-form --registration-form"]) !!}
			<div class="control-group{{ $errors->has('sport_id') ? ' has-error' : '' }}">
				<select class="form-field" required="required" id="sport" name="sport_id">
					<option value="">Select Academy</option>
					<option value="3">Athletics</option>
					<option value="4">Tennis</option>
				</select>
				{{-- {!! Form::select('sport_id',$sports,$sport_id ?? null, ['class'=>'form-field','required' => 'required','placeholder' => 'Select Sports','id'=>'sport']) !!} --}}
				@if ($errors->has('sport_id'))
				<span class="form-error" role="alert">
					<strong>{{ $errors->first('sport_id') }}</strong>
				</span>
				@endif
			</div>
			
			<div class="control-group{{ $errors->has('player_name') ? ' has-error' : '' }}">
				{!! Form::text('player_name', null, ['class'=>'form-field','required' => 'required', 'placeholder'=>'Player Name','id'=>'player_name','autocomplete'=>'off','maxlength'=>'50']) !!}
				@if ($errors->has('player_nam'))
				<span class="form-error">
					<strong>{{ $errors->first('player_name') }}</strong>
				</span>
				@endif
			</div>
			
			<div class="control-group{{ $errors->has('dob') ? ' has-error' : '' }}">
				{!! Form::date('dob', null, ['class'=>'form-field','required' => 'required','id'=>'dob', 'placeholder'=>'Player DOB','autocomplete'=>'off']) !!}
				@if ($errors->has('dob'))
				<span class="form-error">
					<strong>{{ $errors->first('dob') }}</strong>
				</span>
				@endif
			</div>
			
			<div class="control-group{{ $errors->has('name') ? ' has-error' : '' }}">
				{!! Form::text('name', null, ['class'=>'form-field','required' => 'required', 'placeholder'=>'Parent/Guardian Name', 'id'=>'parent_name','autocomplete'=>'off']) !!}
				@if ($errors->has('name'))
				<span class="form-error">
					<strong>{{ $errors->first('name') }}</strong>
				</span>
				@endif
			</div>
			<div class="control-group{{ $errors->has('email') ? ' has-error' : '' }}">
				{!! Form::text('email', null, ['class'=>'form-field','required' => 'required', 'placeholder'=>'Parent/ Guardian Email', 'id'=>'email']) !!}
				@if ($errors->has('email'))
				<span class="form-error">
					<strong>{{ $errors->first('email') }}</strong>
				</span>
				@endif
			</div>
			<div class="control-group{{ $errors->has('mobile') ? ' has-error' : '' }}">
				{!! Form::text('mobile', null, ['class'=>'form-field','required' => 'required', 'placeholder'=>'Parent/Guardian Mobile','id'=>'mobile','maxlength'=>'10']) !!}
				@if ($errors->has('mobile'))
				<span class="form-error">
					<strong>{{ $errors->first('mobile') }}</strong>
				</span>
				@endif
			</div>

			<div class="control-group{{ $errors->has('source') ? ' has-error' : '' }}">
				<select class="form-field" required="required" id="source" name="source">
					<option value="">How did you hear about us?</option>
		            <option value="Facebook">Facebook</option>
		            <option value="Instagram">Instagram</option>
		            <option value="Google Search Ad">Google Search Ad</option>
		            <option value="Google Banner Image">Google Banner Image</option>
		            <option value="Email Newsletter">Email Newsletter</option>
		            <option value="A Friend">A Friend</option>
		            <option value="Other">Other</option>
				</select>
				{{-- {!! Form::select('source',$sports,$source ?? null, ['class'=>'form-field','required' => 'required','placeholder' => 'Select Sports','id'=>'sport']) !!} --}}
				@if ($errors->has('source'))
				<span class="form-error" role="alert">
					<strong>{{ $errors->first('source') }}</strong>
				</span>
				@endif
			</div>


			<div class="control-group{{ $errors->has('g-recaptcha-response') ? ' has-error' : '' }}">
				<div class="g-recaptcha" data-sitekey="{{env('NOCAPTCHA_SITEKEY')}}"></div>
				@if ($errors->has('g-recaptcha-response'))
				<span class="help-block">
					<strong>{{ $errors->first('g-recaptcha-response') }}</strong>
				</span>
				@endif
				
			</div>
			
			
			<div class="control-group mb-10">
				<button type="submit" class="btn --btn-secondary">
				{{ __('Submit') }}
				</button>
			</div>
			{!! Form::hidden('form_type_id',TYPE_POPUP_FORM, ['class'=>'form-field']) !!}
			{!! Form::close() !!}
		</div>
	</div>
</section>


@if(!empty($route) && $route=="tennisacademy" || $route=="tennisacademy-fees" || $route=="tennisacademy-schedule")

	<a href="https://wa.me/971582608408" class="whatsapp" target="_blank">
		<img src="{{ asset('assets-web/images/whatsapp-icon.png')}}" alt="">
	</a>

@elseif(!empty($route) && $route=="athleticsacademy" || $route=="athleticsacademy-fees" || $route=="athleticsacademy-schedule")

	<a href="https://wa.me/971582858239" class="whatsapp" target="_blank">
		<img src="{{ asset('assets-web/images/whatsapp-icon.png')}}" alt="">
	</a>

@else
	
@endif